apiVersion: batch/v1
kind: Job
metadata:
  name: extract-load-init
  namespace: extract-load
spec:
  template:
    spec:
      containers:
      - name: extract-load-init
        image: k3d-myregistry.localhost:12345/extract_load:latest  # extract_load:latest
        imagePullPolicy: Always  # Never
        env:
          - name: WEBSHOP_PORT
            value: '5432'
          - name: WEBSHOP_USER
            value: webshop
          - name: WEBSHOP_DATABASE
            value: postgres
        envFrom:
          - secretRef:
              name: extract-load-secrets
      restartPolicy: Never
  backoffLimit: 5
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: extract-load
  namespace: extract-load
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: extract-load
            image: k3d-myregistry.localhost:12345/extract_load:latest  # extract_load:latest
            imagePullPolicy: Never
            env:
              - name: WEBSHOP_PORT
                value: '5432'
              - name: WEBSHOP_USER
                value: webshop
              - name: WEBSHOP_DATABASE
                value: postgres
            envFrom:
              - secretRef:
                  name: extract-load-secrets
          restartPolicy: Never
      backoffLimit: 5